"""init db

迁移 ID: 8e22b35e41a2
父迁移: 
创建时间: 2026-01-27 19:12:07.029478

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8e22b35e41a2'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abstracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('music_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('file_key', sa.String(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_abstracts')),
    info={'bind_key': ''}
    )
    op.create_table('alias_applies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('music_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SCORING', 'TIMEOUT', 'PASSED', 'ADMIN_PASSED', 'ADMIN_REJECTED', name='aliasstatus'), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alias_applies')),
    info={'bind_key': ''}
    )
    op.create_table('alias_votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alias_votes')),
    info={'bind_key': ''}
    )
    op.create_table('aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('music_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aliases')),
    info={'bind_key': ''}
    )
    op.create_table('user_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_abstract', sa.Boolean(), nullable=False),
    sa.Column('maimai_best_50_style', sa.String(), nullable=False),
    sa.Column('maimai_icon', sa.String(), nullable=True),
    sa.Column('maimai_plate', sa.String(), nullable=True),
    sa.Column('maimai_frame', sa.String(), nullable=True),
    sa.Column('chu_prober_mode', sa.String(), nullable=False),
    sa.Column('create_group', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_configs')),
    info={'bind_key': ''}
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    info={'bind_key': ''}
    )
    op.create_table('bind_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('main_user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('REQUEST', 'CONFIRM', name='bindtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('sub_user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['main_user_id'], ['users.id'], name=op.f('fk_bind_tokens_main_user_id_users')),
    sa.ForeignKeyConstraint(['sub_user_id'], ['users.id'], name=op.f('fk_bind_tokens_sub_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bind_tokens')),
    sa.UniqueConstraint('token'),
    info={'bind_key': ''}
    )
    op.create_table('user_auths',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('ext', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_auths_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_auths')),
    sa.UniqueConstraint('external_id'),
    info={'bind_key': ''}
    )
    op.create_table('user_test_configs',
    sa.Column('reply_uuid', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_test_configs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_test_configs')),
    info={'bind_key': 'test_module'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_test_configs')
    op.drop_table('user_auths')
    op.drop_table('bind_tokens')
    op.drop_table('users')
    op.drop_table('user_configs')
    op.drop_table('aliases')
    op.drop_table('alias_votes')
    op.drop_table('alias_applies')
    op.drop_table('abstracts')
    # ### end Alembic commands ###
